version: "3.8"

services:
  dungeons_and_dragons_bot:
    container_name: dungeons-and-dragons-bot
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PROJECT_DIR=${PROJECT_DIR}
    links:
      - database
    volumes:
      - ./src/:${PROJECT_DIR}/src/
      - ./game_data/:${PROJECT_DIR}/game_data/
      - ./logs/:${PROJECT_DIR}/logs/

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - ./database/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
