name: Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt
          export PROJECT_DIR=$(pwd)

      - name: Run tests
        run:  python -m pytest
